apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: cloudpack
spec:
  selector:
    app: agent-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
