apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cloudpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: cloudpack-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: AGENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudpack-config
                  key: AGENT_SERVICE_URL

            - name: WEATHER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudpack-config
                  key: WEATHER_SERVICE_URL

            - name: MEMORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudpack-config
                  key: MEMORY_SERVICE_URL
