apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-service
  namespace: cloudpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-service
  template:
    metadata:
      labels:
        app: memory-service
    spec:
      containers:
        - name: memory-service
          image: cloudpack-memory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
