apiVersion: v1
kind: Service
metadata:
  name: memory-service
  namespace: cloudpack
spec:
  selector:
    app: memory-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
