apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  namespace: cloudpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
        - name: weather-service
          image: cloudpack-weather-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudpack-secrets
                  key: OPENWEATHER_API_KEY
